/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Config {
  $schema?: string;
  extends?: string[];
  presets?: {
    [k: string]: (
      | {
          type: "file";
          path: string;
          content:
            | {
                path: string;
              }
            | {
                url: string;
              }
            | string;
        }
      | {
          type: "preset";
          name: string;
        }
      | {
          type: "lines";
          path: string;
          content:
            | {
                path: string;
              }
            | {
                url: string;
              }
            | string;
        }
      | {
          type: "reset";
          path: string;
        }
      | {
          type: "delete";
          path: string;
        }
      | {
          type: "init";
          path: string;
          content:
            | {
                path: string;
              }
            | {
                url: string;
              }
            | string;
        }
      | {
          type: "merge";
          path: string;
          mergeArrays: boolean;
          content:
            | {
                path: string;
              }
            | {
                url: string;
              }
            | string;
        }
      | {
          type: "part";
          path: string;
          content:
            | {
                path: string;
              }
            | {
                url: string;
              }
            | string;
          strategy: "start" | "end" | "content";
        }
    )[];
  };
  rules?: (
    | {
        type: "file";
        path: string;
        content:
          | {
              path: string;
            }
          | {
              url: string;
            }
          | string;
      }
    | {
        type: "preset";
        name: string;
      }
    | {
        type: "lines";
        path: string;
        content:
          | {
              path: string;
            }
          | {
              url: string;
            }
          | string;
      }
    | {
        type: "reset";
        path: string;
      }
    | {
        type: "delete";
        path: string;
      }
    | {
        type: "init";
        path: string;
        content:
          | {
              path: string;
            }
          | {
              url: string;
            }
          | string;
      }
    | {
        type: "merge";
        path: string;
        mergeArrays: boolean;
        content:
          | {
              path: string;
            }
          | {
              url: string;
            }
          | string;
      }
    | {
        type: "part";
        path: string;
        content:
          | {
              path: string;
            }
          | {
              url: string;
            }
          | string;
        strategy: "start" | "end" | "content";
      }
  )[];
}
