name: Test

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: michaelmass/actions/tilt-setup@master
      - working-directory: test
        run: tilt ci
